/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.*;
import java.awt.Color;
import java.net.MalformedURLException;
import java.rmi.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alvaro y patricia
 */
public class InterfazRemota extends javax.swing.JFrame {

    private InterfazVigilancia interfazVigilancia;
    private boolean parado = false;

    /**
     * Creates new form InterfazRemota
     */
    public InterfazRemota() throws NotBoundException, MalformedURLException, RemoteException {
        initComponents();
        interfazVigilancia = (InterfazVigilancia) Naming.lookup("//localhost/ModuloDeControl");
        botonParar.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cansancio1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BuscarID2 = new javax.swing.JButton();
        cantidadMenores1 = new javax.swing.JTextField();
        atraccionID1 = new javax.swing.JTextField();
        BuscarID = new javax.swing.JButton();
        idABuscar = new javax.swing.JTextField();
        atraccionID = new javax.swing.JTextField();
        cansancio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        controlMenores = new javax.swing.JButton();
        cantidadMenores = new javax.swing.JTextField();
        tobogan3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        toboganes = new javax.swing.JButton();
        tobogan1 = new javax.swing.JTextField();
        tobogan2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vestuario = new javax.swing.JTextField();
        botonAforo = new javax.swing.JButton();
        piscinaOlas = new javax.swing.JTextField();
        piscinaNinos = new javax.swing.JTextField();
        piscinaGrande = new javax.swing.JTextField();
        aforoToboganes = new javax.swing.JTextField();
        tumbonas = new javax.swing.JTextField();
        botonParar = new javax.swing.JButton();

        jLabel3.setText("Control de Menores");

        BuscarID2.setText("Buscar");
        BuscarID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarID2ActionPerformed(evt);
            }
        });

        cantidadMenores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMenores1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BuscarID.setText("Buscar");
        BuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarIDActionPerformed(evt);
            }
        });

        idABuscar.setText("ID-Usuario");
        idABuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idABuscarActionPerformed(evt);
            }
        });

        atraccionID.setEditable(false);
        atraccionID.setText("Ubicacion");

        cansancio.setEditable(false);
        cansancio.setText("Actividades");

        jLabel1.setText("Control de Ubicacion");

        jLabel2.setText("Control de Menores");

        controlMenores.setText("Buscar");
        controlMenores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlMenoresActionPerformed(evt);
            }
        });

        cantidadMenores.setEditable(false);
        cantidadMenores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMenoresActionPerformed(evt);
            }
        });

        tobogan3.setEditable(false);

        jLabel4.setText("Control de Toboganes");

        toboganes.setText("Buscar");
        toboganes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toboganesActionPerformed(evt);
            }
        });

        tobogan1.setEditable(false);
        tobogan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tobogan1ActionPerformed(evt);
            }
        });

        tobogan2.setEditable(false);

        jLabel5.setText("Tobogan A");

        jLabel6.setText("Tobogan C");

        jLabel7.setText("Tobogan B");

        jLabel8.setText("Control de Aforo");

        vestuario.setEditable(false);
        vestuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vestuarioActionPerformed(evt);
            }
        });

        botonAforo.setText("Buscar");
        botonAforo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAforoActionPerformed(evt);
            }
        });

        piscinaOlas.setEditable(false);
        piscinaOlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piscinaOlasActionPerformed(evt);
            }
        });

        piscinaNinos.setEditable(false);
        piscinaNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piscinaNinosActionPerformed(evt);
            }
        });

        piscinaGrande.setEditable(false);
        piscinaGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piscinaGrandeActionPerformed(evt);
            }
        });

        aforoToboganes.setEditable(false);
        aforoToboganes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aforoToboganesActionPerformed(evt);
            }
        });

        tumbonas.setEditable(false);

        botonParar.setText("PARAR");
        botonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonParar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(149, 149, 149))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idABuscar)
                                    .addComponent(atraccionID)
                                    .addComponent(cansancio)
                                    .addComponent(BuscarID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cantidadMenores)
                                            .addComponent(controlMenores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2))
                                        .addGap(83, 83, 83)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tobogan1)
                                            .addComponent(tobogan2)
                                            .addComponent(tobogan3)
                                            .addComponent(toboganes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(148, 148, 148))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(150, 150, 150)))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonAforo, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(vestuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(piscinaGrande)
                            .addComponent(piscinaOlas)
                            .addComponent(piscinaNinos)
                            .addComponent(aforoToboganes)
                            .addComponent(tumbonas)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel8)))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(cantidadMenores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)
                                .addComponent(idABuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(atraccionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(cansancio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(piscinaOlas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tobogan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(7, 7, 7)
                                        .addComponent(tobogan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tobogan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(tumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(piscinaNinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(piscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aforoToboganes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonAforo)
                                    .addComponent(toboganes)
                                    .addComponent(controlMenores)
                                    .addComponent(BuscarID)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vestuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(botonParar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarIDActionPerformed
        try {
            // TODO add your handling code here:
            String[] parametros = interfazVigilancia.controlUbicacion(idABuscar.getText());
            atraccionID.setText(parametros[0]);
            cansancio.setText(parametros[1]);
        } catch (RemoteException ex) {
            Logger.getLogger(InterfazRemota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BuscarIDActionPerformed

    private void idABuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idABuscarActionPerformed

    }//GEN-LAST:event_idABuscarActionPerformed

    private void controlMenoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlMenoresActionPerformed
        // TODO add your handling code here:
        try {
            cantidadMenores.setText(interfazVigilancia.buscarMenores());
        } catch (RemoteException ex) {
            Logger.getLogger(InterfazRemota.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_controlMenoresActionPerformed

    private void cantidadMenoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMenoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadMenoresActionPerformed

    private void BuscarID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarID2ActionPerformed

    private void cantidadMenores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMenores1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadMenores1ActionPerformed

    private void toboganesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toboganesActionPerformed
        try {
            // TODO add your handling code here:
            String[] parametros = interfazVigilancia.controlToboganes();
            tobogan1.setText(parametros[0]);
            tobogan2.setText(parametros[1]);
            tobogan3.setText(parametros[2]);

        } catch (RemoteException ex) {
            Logger.getLogger(InterfazRemota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_toboganesActionPerformed

    private void tobogan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tobogan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tobogan1ActionPerformed

    private void vestuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vestuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vestuarioActionPerformed

    private void piscinaNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piscinaNinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piscinaNinosActionPerformed

    private void piscinaGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piscinaGrandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piscinaGrandeActionPerformed

    private void piscinaOlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piscinaOlasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piscinaOlasActionPerformed

    private void aforoToboganesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aforoToboganesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aforoToboganesActionPerformed

    private void botonAforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAforoActionPerformed
        try {
            // TODO add your handling code here:
            String[] parametros = interfazVigilancia.usuariosZona();
            vestuario.setText(parametros[0]);
            piscinaOlas.setText(parametros[1]);
            piscinaNinos.setText(parametros[2]);
            piscinaGrande.setText(parametros[3]);
            tumbonas.setText(parametros[4]);
            aforoToboganes.setText(parametros[8]);
        } catch (RemoteException ex) {
            Logger.getLogger(InterfazRemota.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonAforoActionPerformed

    private void botonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPararActionPerformed
        try {
            if (!parado) {
                parado = true;
                interfazVigilancia.alternar();
                botonParar.setText("RENAUDAR");
                botonParar.setBackground(Color.green);
            } else {
                parado = false;
                interfazVigilancia.alternar();
                botonParar.setText("PARAR");
                botonParar.setBackground(Color.red);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_botonPararActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRemota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRemota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRemota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRemota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazRemota().setVisible(true);
                } catch (NotBoundException ex) {
                    Logger.getLogger(InterfazRemota.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(InterfazRemota.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException ex) {
                    Logger.getLogger(InterfazRemota.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarID;
    private javax.swing.JButton BuscarID2;
    private javax.swing.JTextField aforoToboganes;
    private javax.swing.JTextField atraccionID;
    private javax.swing.JTextField atraccionID1;
    private javax.swing.JButton botonAforo;
    private javax.swing.JButton botonParar;
    private javax.swing.JTextField cansancio;
    private javax.swing.JTextField cansancio1;
    private javax.swing.JTextField cantidadMenores;
    private javax.swing.JTextField cantidadMenores1;
    private javax.swing.JButton controlMenores;
    private javax.swing.JTextField idABuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField piscinaGrande;
    private javax.swing.JTextField piscinaNinos;
    private javax.swing.JTextField piscinaOlas;
    private javax.swing.JTextField tobogan1;
    private javax.swing.JTextField tobogan2;
    private javax.swing.JTextField tobogan3;
    private javax.swing.JButton toboganes;
    private javax.swing.JTextField tumbonas;
    private javax.swing.JTextField vestuario;
    // End of variables declaration//GEN-END:variables
}
